sudo: false
language: node_js
env:
  - NODE_ENV=development
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "6"
before_install:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npm i -g audit-ci; fi
script:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then audit-ci --moderate; fi
  - npm test